### ISSUE TITLE
Upgrade to React 15.X

### ISSUE THREAD

**Issue by Serfenia** [christianalfoni/flux-react#11]
Hello Christian,

Is it possible to upgrade this to support React 15.X?

Regards,
Patrick van Vuuren

**Comment by christianalfoni** [comment]
For sure, if you have the time it would be really great if you created a pull on it :) Just update the package.json file

**Comment by Serfenia** [comment]
Done, builds are failing but the last dozens of builds have been failing so not sure if that is an issue.

**Comment by Serfenia** [comment]
Resolved by #12 
@christianalfoni Could you publish it to npm? Thanks!

**Comment by christianalfoni** [comment]
Cool, done :)
