### ISSUE TITLE
Lack of support for ArrayBuffer, Blob & File in IE9

### ISSUE THREAD

**Issue by rdjpalmer** [christianalfoni/flux-react#2]
```
  if (!obj || "object" !== typeof obj || obj instanceof ArrayBuffer || obj instanceof Blob || obj instanceof File) return obj;
```

https://github.com/christianalfoni/flux-react/blob/master/src/safeDeepClone.js#L5

IE9 doesn't support ArrayBuffer, Blob or File out of the box. I can successfully polyfill [ArrayBuffer](https://github.com/inexorabletash/polyfill/blob/master/typedarray.js) & [Blob](https://github.com/eligrey/Blob.js/blob/master/Blob.js), but I've not been able to find a working polyfill for `File`. My thought is that if the browser doesn't support them, we don't need to check for them in the first place.

Suggesting that we check for support for each one & check against them. I'll put a PR request together for a first pass, but any thoughts on it prior would be good.

**Comment by sergiobertolazo** [comment]
i have the same problem, how i can make it work?
