### ISSUE TITLE
Implement workaround for inconsistent EventEmitter2 module export

### ISSUE THREAD

**Issue by VictorBlomberg** [christianalfoni/flux-react#4]
Hi,

flux-ract does currently not work when the EventEmitter2 module is loaded via AMD (see PR https://github.com/asyncly/EventEmitter2/pull/122 and issue https://github.com/asyncly/EventEmitter2/issues/121). Since the EventEmitter2 export favors AMD over CommonJS, and webpack supports both, using flux-react with webpack is not straight forward.

Changing [action.js:9](https://github.com/christianalfoni/flux-react/blob/master/src/action.js#L9) and [main.js:5](https://github.com/christianalfoni/flux-react/blob/master/src/main.js#L5) from
``var EventEmitter = require('eventemitter2').EventEmitter2;``
to
``var EventEmitter = require('eventemitter2').EventEmitter2 || require('eventemitter2');``
would solve the issue.

Since the bug hasn't been fixed for quite a while in EventEmitter2, it would be nice if this workaround could be implemented here.

Victor Blomberg

**Comment by christianalfoni** [comment]
Makes sense Victor, new version is out, thanks for bringing it to my attention :-)

**Comment by VictorBlomberg** [comment]
Thank you!
