### ISSUE TITLE
Actions - Return promise when all stores are done with the action

### ISSUE THREAD

**Issue by Serfenia** [christianalfoni/flux-react#6]
Hey Christian

I had some idea about the actions.
Currently you have to execute an action you do like: `actions.someAction(params)`.

Is it possible to return a promise when the action is finished (i.e. a store function is fully executed and finished).

Example:

```
var actions = require('./../actions.js');
var component = React.createClass({
  someFunction: function(params) {
    actions.someAction(params)
        .then(function() {})
        .error(function() {})
        .finally(function() {});
  }
});
```

This way it makes them also more testable using for example Jest using `pit`:

```
pit('Spec 1', function() {
  return actions.someActions(params).then(function(stuff) {
    expect(val1).toBe(val2);
  });
});
```

Regards,
Patrick

**Comment by christianalfoni** [comment]
Hi @Serfenia,

It is very tempting to add this functionality, I have discussed this a lot with colleagues :-) The thing is that this breaks with the principle of flux. It should be a one way flow. Adding promises will cause the flow to go in reverse and it will get harder to reason about your app. In an isolated example it is not a problem.

Events do feel a bit "less trustworthy" when doing testing. But that is the flow you want to test, because that is the flow that you want your app to run in ;-)

Please let me know if you think I misunderstand something, I often do, hehe. But the "one way flow" of flux is really important and actions with promises would break that principle.

**Comment by Serfenia** [comment]
Hi @christianalfoni 

I understand you see it that way. The idea I have is that it returns a succes when the stores are finished doing their stuff. Basically you could see it as that the stores say 'I'm done!' or 'Something went wrong!'. Currently they do that through emitting a certain change, but not as callback of the original action. The problem with that is if a component invokes an action and it's not a component that is listening to changes of the store(s) that contains that action, it will never know if it succeeded, and for testing you have to use things like timeout to be able to test this. 

I agree on your point when about the one way flow. But that flow is about how the 'data' should flow. And from my point of view that data is data that comes from your server or web storage that is actually used to show something in your web application, not a message about telling something went good or bad.

**Comment by christianalfoni** [comment]
Hi again @Serfenia,

Yeah, I see your point, but maybe we could take a look at a test you have written? There might be a way to create a testing specific util for example :-)

**Comment by Serfenia** [comment]
Hey @christianalfoni 

A test case like this would suit this:

~~~
// Jest

jest.dontMock('../Component');
jest.dontMock('../../actions/actions.js');
describe('Component', function() {
  var React   =  require('react/addons');
  var TestUtils = React.addons.TestUtils;
  var actions =  require('../../actions/actions.js');
  var objectThatActsAsParent = {
    handleUpdate: function() {}
  };
  var component = require('../Component');

  beforeEach(function() {
    objectThatActsAsParent.handleUpdate = jest.genMockFunction();
    var component = TestUtils.renderIntoDocument(
      <Component onUpdate={objectThatActsAsParent.handleUpdate} />
    )
  });
  
  pit('Should call the parent's update function when action A is triggered and the stores have been emitted', function() {
     return actions.someAction().then(function() {
        expect(objectThatActsAsParent.handleUpdate).toBeCalled();
     }
   }
});
~~~

Imagine that the component has added a listener to some store that has implemented `someAction`. This listener does something like: `this.props.onUpdate(data)`

Currently I have to use `run` and `waitsFor` forcing the test case to wait for like 1500ms using `Date.now()` differences (Jest auto-mocks setTimeout) so I am sure the stores have been emitted.

**Comment by christianalfoni** [comment]
Hi @Serfenia ,

Thanks for adding an example :-) The way I would test this component is:

// Jest

jest.dontMock('../Component');
jest.dontMock('../../stores/someStore.js');
jest.dontMock('../../actions/actions.js');
describe('Component', function() {
  var React   =  require('react/addons');
  var TestUtils = React.addons.TestUtils;
  var actions =  require('../../actions/actions.js');
  var objectThatActsAsParent = {
    handleUpdate: function() {}
  };
  var component = require('../Component');

  beforeEach(function() {
    objectThatActsAsParent.handleUpdate = jest.genMockFunction();
    var component = TestUtils.renderIntoDocument(
      <Component onUpdate={objectThatActsAsParent.handleUpdate} />
    )
  });

  pit('Should call the parent's update function when action A is triggered and the stores have been emitted', function(done) {
     someStore.once('change', function () {
       expect(objectThatActsAsParent.handleUpdate).toBeCalled(); 
       done();
     });
    actions.someAction();
   }
});

In this case it would be nice with a "reset store" method for each test. But you see challenges with this approach?

**Comment by Serfenia** [comment]
You have no assurance that the `handleUpdate` of the parent object is already called when the function in the test executes, because the callback of the store is triggered. If the listeners are in a particular order where the listener of the component fires before the function in the test, then it won't work. And because you render the component before every test, my guess that listener of the component will fire before the listener in the `pit` test.

**Comment by AMalininHere** [comment]
I think that your application should control actions but not vice versa. For example: you create new todo item and application triggers action(todo.add). After that application sends data to server and after response application triggers action(todo.saved).
It should be easy to understand.

**Comment by christianalfoni** [comment]
Hi again @Serfenia ,

Yeah, you definitely have a point. I would suggest that calling an action should trigger a a specific flow regarding store change events. So there will always be a specific number of times the onUpdate callback triggers. That said, if something changes in the code, one test can leak into another test as suddenly some change event is triggered asynchronously and that is not taken into account in a test. But this is an async problem really.

There is really no way a store can know when it is done emitting events, as any async behaviour inside a store can trigger an event. It would require every async behaviour to return a promise, which is not what a store is supposed to do really.

But what we are talking about here is why "Action Creators" came about. Testing async behaviour inside a store is very difficult. So there should not be any async behaviour inside them, rather an "Action Creator" should trigger multiple synchronous actions. Let me give an example:

```js
var actions = flux.createActions([
  'addItem',
  'removeItem',
  'updateItem'
]);

var ActionCreators = {
  createItem: function (item) {
    actions.addItem(item); // Synchronously handled inside the store
    ajax.post('/items', item)
      .success(function (id) {
         actions.updateItem(item, id);
       })
       .error(function () {
         actions.removeItem(item);
       });
  } 
};
```

So in you tests you would just trigger the specific actions, not the action creators. Your actions are always synchronous so any test will ensure to be finished before the next. Then you would mock the actions when testing ActionCreators.

Did that make sense?
