### ISSUE TITLE
React peer dependency

### ISSUE THREAD

**Issue by glasseyes42** [christianalfoni/flux-react#7]
Hi there,

Only through reinstalling react did I discover that at 2.6.5 it wasn't happy to install due to peer dependency requirements in flux-react. Personal (small) testing haven't found any issues... any plans to update?

Thanks.

**Comment by christianalfoni** [comment]
Hi @glasseyes42 ,

Deps should now be updated :-) Thanks for pointing it out!

**Comment by jeromecovington** [comment]
Does this peer dependency interfere with using flux-react in a react native app?

**Comment by christianalfoni** [comment]
I think you should be okay here. As the latest version of React requires either `react-dom` or `reactive-native` for rendering. It is the same React package for both.

**Comment by jeromecovington** [comment]
Thanks! So I ended up rolling my own stores/actions for the react-native project, I will revisit flux-react at a later date.
