### ISSUE TITLE
React 0.14.0 support?

### ISSUE THREAD

**Issue by varandpez** [christianalfoni/flux-react#9]
Hi guys, wanted to know if you have React 0.14.x support in mind?

Thanks.

**Comment by joernroeder** [comment]
yeah! 0.14.x support would be great!

**Comment by louy** [comment]
@christianalfoni is this project dead?

**Comment by echoescn** [comment]
@louy I think so

**Comment by Nokrosis** [comment]
Does anyone wants to fork and update?

**Comment by christianalfoni** [comment]
Project already has 0.14 support, you have problems with any specific version of npm? I updated to only support 0.14 now. Hope that fixes it :-)

The project has a pretty low priority, have a bit too much on my hands. If any of you want to be added as contributor I would love to add you :-)

New version released now
